---
- name: Create target directory
  file: 
    path: '{{adop_home}}/adop-docker-compose'
    state: directory
    owner: centos
    group: centos

- name: Clone adop-docker-compose
  git:
    repo: '{{adop_reporitory}}'
    dest: '{{adop_home}}/adop-docker-compose'
    version: '{{adop_version}}'
