---
- name: Clone adop-docker-compose
  git:
    repo: '{{adop_reporitory}}'
    dest: '{{adop_home}}/adop-docker-compose'
    version: '{{adop_version}}'
    force: yes

- name: Change owners 
  file: 
    path: '{{adop_home}}/adop-docker-compose'
    owner: centos
    group: centos
