---
- name: Create target directory
  file: 
    path: /src/www 
    state: directory
    owner: centos
    owner: centos

- name: Clone adop-docker-compose
  git:
    repo: '{{adop_reporitory}}'
    dest: '{{adop_home}}/adop-docker-compose'
    version: '{{adop_version}}'
