---
- name: yum update
  yum: name=* state=latest update_cache=yes

- name: yum install utilities 
  yum: 
    name:
      - git 
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
    state: present

- name: Update file descriptors in sysctl
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes